### ISSUE TITLE
CrashLoopBackOff v1.10.3

### ISSUE THREAD

**Issue by chris93111** [knative-extensions/eventing-natss#434]
**Describe the bug**
```
panic: runtime error: index out of range [1024] with length 1024
goroutine 215 [running]:
encoding/base64.(*Encoding).Encode(0x1bfe220?, {0xc00087b400?, 0x3dc?, 0x4?}, {0xc00087bc00?, 0xc000669198?, 0xc000669388?})
	encoding/base64/base64.go:158 +0x26f
knative.dev/eventing/pkg/channel.(*MessageDispatcherImpl).dispatchExecutionInfoTransformers(0xc0005de150, 0x1?, 0xc0009eca80)
	knative.dev/eventing@v0.37.0/pkg/channel/message_dispatcher.go:324 +0x4fe
knative.dev/eventing/pkg/channel.(*MessageDispatcherImpl).DispatchMessageWithRetries(0xc0005de150, {0x1f63a60, 0xc0009ec900}, {0x1f639f0, 0xc00086e170}, 0xc0009ec960, 0xc0007fad80?, 0xc0007fae10, 0xc0007faea0, 0xc00059cd80, ...)
	knative.dev/eventing@v0.37.0/pkg/channel/message_dispatcher.go:140 +0xf28
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).doHandle(0xc000397b90, {0x1f63a60, 0xc0009ec900}, 0xc00050a1c0)
	knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:168 +0x628
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler.func2.1(0xc000083db0?, 0xc000669de0, 0x1f44340?, {0x1f63a60?, 0xc0009ec900?}, 0x10?)
	knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:107 +0x48
knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler.func2()
	knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:108 +0x6e
created by knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher.(*Consumer).MsgHandler in goroutine 161
	knative.dev/eventing-natss/pkg/channel/jetstream/dispatcher/consumer.go:101 +0x2f3
```

 **Knative release version**

1.9

**Comment by astelmashenko** [comment]
I did not test with knative 1.9. Eventing-natss 1.10 should be used with knative-eventing 1.10. Could you please try to reproduce with eventing 1.10.x?

**Comment by astelmashenko** [comment]
I did not check `deadlettersink`, will try to use it.
